### PR TITLE
Add support for email HTML with text version:

### PR DESCRIPTION
**Pull request by ucotta**
- Use content attribute for HTML version
- Use the new "text" attribute for TEXT version.

### CODE REVIEW

**Comment by iamjono** [comment]
IMHO looks good, however further to this I would suggest that if it's a text only email, probably should have a if html.isEmpty condition too?

**Comment by ucotta** [comment]
Hi!,

I changed multipart too, no it works with text, html and both.

Un saludo,
Ubaldo


--
Ubaldo Cotta
ucotta@me.com
Móvil: 658 924 996
Consultor IT - Diseño WEB - APP iPad / iPhone - LAMP

**Comment by iamjono** [comment]
Looks excellent. 
Rocky, I'm merging and tagging, let me know if you have any concerns?

**Comment by RockfordWei** [comment]
Well, if it passed all tests, I didn't see it why not. My only concern is ... today's mail servers are very sensitive to junk mails, so HTML may be not the only reason being blocked...

**Comment by iamjono** [comment]
The point is not about blocking, but about the fact that it *should* support HTML & plain text together like it is now.

**Pull request merged**
